workflows:
  ios-workflow:
    name: iOS Build & TestFlight
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - "your-email@example.com"
