platform :ios, '13.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  # Pods for Runner
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  # هر کتابخونه‌ای که بعداً لازم شد اینجا اضافه کن
end

